version: '2.2'

services:

  imagination_server:
    # Please add your service here and serve it on port 5000.
    build:
      dockerfile: src/Imagination.Server/Imagination.Server/Dockerfile
      context: .
    mem_limit: 512m
    mem_reservation: 512m
    ports:
      - "5000:5000"
    depends_on:
      - jaeger
      - httpbin
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268/tcp"
      - "14250:14250/tcp"
      - "16686:16686"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
